# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: xiao_ble
    shield: lism_left rgbled_adapter
    artifact-name: lism_left_non_trackball
    overlay-path: zmk-keyboards-LisM/boards/shields/lism/non_trackball_l.overlay
  - board: xiao_ble
    shield: lism_left rgbled_adapter
    artifact-name: lism_left_trackball
    overlay-path: zmk-keyboards-LisM/boards/shields/lism/trackball_l.overlay
  - board: xiao_ble
    shield: lism_right rgbled_adapter
    artifact-name: lism_right_non_trackball
    overlay-path: zmk-keyboards-LisM/boards/shields/lism/non_trackball_r.overlay
  - board: xiao_ble
    shield: lism_right rgbled_adapter
    artifact-name: lism_right_trackball
    overlay-path: zmk-keyboards-LisM/boards/shields/lism/trackball_r.overlay

  - board: xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-xiao_ble-zmk

  - board: xiao_ble
    shield: lism_right rgbled_adapter
    artifact-name: lism_right_non_trackball_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    overlay-path: zmk-keyboards-LisM/boards/shields/lism/non_trackball_r.overlay
  - board: xiao_ble
    shield: lism_right rgbled_adapter
    artifact-name: lism_right_trackball_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    overlay-path: zmk-keyboards-LisM/boards/shields/lism/trackball_r.overlay
